# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java App with Maven/Sonar

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Cacheado de Maven para acelerar el despliegue
      uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Check pom.xml exits
      run: |
             if [ ! -f "${GITHUB_WORKSPACE}/pom.xml" ]; then
             echo "el fichero pom.xml no existe en el espacio de trabajo ${GITHUB_WORKSPACE}"
             fi
    - name: Check test classes
      run: |
            if [ ! -f "${GITHUB_WORKSPACE}/src/test" ]; then
            echo "no esta creado el directorio de test"
            fi         
    - name: Maven clean compile
      run: mvn -B clean compile --file pom.xml        
 #   - name: SonarQube Scan
 #     uses: sonarsource/sonarqube-scan-action@master
 #     with:
 #        projectBaseDir: src
 #        args: >
 #              -Dsonar.verbose=true
 #              -Dsonar.projectKey=demoapp
 #     env:
 #        SONAR_TOKEN: ${{ secrets.SONAR_SECRET }}
 #        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
 #   - name: SonarQube QualityGate    
 #     uses: sonarsource/sonarqube-quality-gate-action@master
 #     env:
  #        SONAR_TOKEN: ${{ secrets.SONAR_SECRET }}
  #        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}      
    - name: Maven validate
      run: mvn -B validate --file pom.xml
    - name: Maven test
      run: mvn -B test --file pom.xml
    - name: Publish Test Report
      if: success() || failure()
      uses: scacap/action-surefire-report@v1  
    - name: Maven package
      run: mvn -B package --file pom.xml
      
