# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java App with Maven/Sonar

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Cache the Maven packages to speed up build
      uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@master
      with:
         projectBaseDir: src
         args: >
               -Dsonar.verbose=true
      env:
         SONAR_TOKEN: ${{ secrets.SONAR_SECRET }}
         SONAR_URL: ${{ secrets.SONAR_URL }}
    - name: Maven validate
      run: mvn -B validate --file pom.xml
    - name: Maven clean compile
      run: mvn -X compile --file pom.xml
    - name: Maven test
      run: mvn -B test --file pom.xml
    - name: Maven package
      run: mvn -B package --file pom.xml
      
